#!/bin/bash
# Pombo Docker
#by Slackwarecps

echo '======================================================================================='
echo '|           POMBO DOCKER            1.0                                               |'
echo '======================================================================================='
PS3='choise your seu pru! pru! : '
options=("docker:apagar containers" "Subir Backend" "backend:reiniciar" "Sair pru!")
options2=(1,2,3,4)
echo '1) docker:erase all containers                      | 9) Setup pombodocker'
echo '2) enable sonarqube                                 | X)'
echo '3) disable sonarqube"                               | X)'  
echo '4) exit                                             | X)'
echo '5) pru!                                             | X)'
echo '6) containers running... (Docker ps)                | X)'
echo '7) Available Images (docker images)                 | X)'
echo '8) Show All containers - ON and OFF (docker ps -a)  | X)'

echo ""
echo ""
echo "Type your option:"
read n
case $n in
    1)
     clear
     echo "killing all containers "
     sleep 1
    LISTA=$(docker ps -q)
    docker stop -t 0 $LISTA
    pombo
    ;;

    
    2) docker start pombosonarqube
       sleep 2
       echo 'acess it using http://localhost:9077'
       sleep 3
       clear
       
       pombo
       ;;
    3) docker stop -t 0 $(docker ps -aqf "name=pombosonarqube")
      
      pombo
    
    ;;
    4) 
    clear
    echo 'bye bye! pru!'
    
    exit;;
    6) 
    clear
    docker ps
    pombo
    ;;
    5)
    clear
    echo "pru! pru!"
    sleep 1
    echo "wait please..."
     sleep 2
     clear
     pombo
     ;;
    7)
    clear
    docker images
    pombo    
    ;;
    8)
    clear
    docker ps -a
    pombo    
    ;;    
    9)
    clear
    docker run -d --name pombosonarqube -p 9077:9000 -p 9092:9092 sonarqube
    pombo    
    ;; 
    
    *) 
    clear
    echo 'not a valid option try again! pru!'
    sleep 1
    clear
    pombo
    ;;
esac
